DROP TABLE IF EXISTS TBL_EMPLOYEES;
  
CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  word_cnt NUMBER NOT NULL,
  data1 VARCHAR(250),
  data2 VARCHAR(250),
  data3 VARCHAR(250),
  data4 VARCHAR(250)
);